### ISSUE TITLE
Unable to create Image from Git project

### ISSUE THREAD

**Issue by ravieze** [kamon-io/docker-grafana-graphite#123]
This is what i did

1. checkout the git repo (from master)
2. run the command: docker build -t rc/graphite-grafana .

once the image is done, i changed the docker-compose.json to refer to my new image. Now i run the command: make up. The containers are up, but there is no UI

if i use the kamon/graphite-grafana things work very smooth. Any help?

**Comment by paulosuzart** [comment]
Try adding this:
```
    location /static {
      alias /opt/graphite/webapp/content;
    }
```
to `nginx.conf` at `server` listening port 81. Basically nginx is not serving the static content (js,css,img) from the proper folder.

Need to create a pr for this but short of time now.

**Comment by MrNeuronix** [comment]
Same issue, comment above doesn't help

**Comment by paulosuzart** [comment]
Hi, This is working for us with the master version and the `docker-compose.yml` set to:

```
version: '2'
services:
  grafana_graphite:
    build: .
    container_name: kamon-grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
      - '8000:8000'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./log/supervisor:/var/log/supervisor
```
You can also use docker-compose directly to build the service after this change: `docker-compose build grafana_graphite` then `make up`. Have you tried this way?
